# Generated by Django 4.0.4 on 2022-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
