# Generated by Django 4.0.4 on 2022-04-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_bursary_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursary',
            name='invited_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
