# Generated by Django 4.0.4 on 2022-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('outdoor_number', models.IntegerField()),
                ('interior_number', models.IntegerField()),
                ('suburb', models.CharField(max_length=100)),
                ('cp', models.BigIntegerField()),
                ('municipality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone_number', models.BigIntegerField()),
                ('way_pay', models.CharField(max_length=100)),
                ('bill_usage', models.CharField(max_length=250)),
            ],
        ),
    ]
