# Generated by Django 4.0.4 on 2022-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='regime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
