# Generated by Django 4.0.4 on 2022-04-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('persons', models.IntegerField()),
            ],
        ),
    ]
