# Generated by Django 4.0.4 on 2022-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('cp', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('company_institution', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('professional_license', models.CharField(max_length=255)),
                ('specialty_certificate', models.CharField(max_length=255)),
            ],
        ),
    ]
