# Generated by Django 4.0.4 on 2022-04-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cell_phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
