# Generated by Django 4.0.4 on 2022-04-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_cell_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='price_pay',
            field=models.BigIntegerField(null=True),
        ),
    ]
