# Generated by Django 4.0.4 on 2022-04-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_categorycourse_course'),
        ('users', '0003_users_price_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='course_pre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related_pre', to='courses.course'),
        ),
        migrations.AddField(
            model_name='users',
            name='course_trans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related_trans', to='courses.course'),
        ),
    ]
