# Generated by Django 4.0.4 on 2022-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_course_pre_users_course_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='price_pay',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
