# Generated by Django 4.0.4 on 2022-05-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='professional_license',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='specialty_certificate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
